# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tips' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tips
  pod 'Alamofire'

  target 'TipsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TipsUITests' do
    # Pods for testing
  end

end
