# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'Tips' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tips
  pod 'Alamofire'
  pod 'SwiftMessages'
  pod "Device", '~> 3.6.0'
  pod 'RealmSwift'

  target 'TipsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TipsUITests' do
    # Pods for testing
  end

end
